### ISSUE TITLE
Error when building using Webpack

### ISSUE THREAD

**Issue by pingshunhuangalex** [shershen08/vue-masonry#26]
Hi @shershen08 

Thanks for the amazing tool here, and everything works as it should. However, when I tried to bundle everything in `Webpack` (I used `Vue-cli`), the below error showed up.

```
ERROR in static/js/vendor.6534844124b38bd29711.js from UglifyJs
Unexpected token: operator (>) [./node_modules/vue-masonry/src/masonry.plugin.js:19,0][static/js/vendor.6534844124b38bd29711.js:41470,27]
```

I looked more in details into the above directory, it looks like the following line is causing the problem, but I can't seem to find out why. Maybe you can discover something I missed here. Thanks.

`const stringToBool = val => (val + '').toLowerCase() === 'true'`

**Comment by shershen08** [comment]
Hello @pingshunhuangalex 

Please check the same issue I hand recently - https://github.com/shershen08/vue-masonry/issues/24

Can you check in what way your setup is different from - https://github.com/shershen08/vue-masonry-plugin-demo

**Comment by pingshunhuangalex** [comment]
Hi @shershen08 
I did check the other issue thread and tried all the possible ways mentioned in it, but no luck. I also tried to cross-reference your demo repo, no luck either.

I noticed that in your repo, you included the uglifyJS in your dev. How is that gonna help solve the build issue since we are talking about bundling for production? Also I'm also using Vue-cli which has already included uglifyJS, and they do have one issue about uglifying ES6 files that is still open.

I'm not sure how I can illustrate my issue more and I can't really provide repo for testing. May I ask if it's possible for you to compile your ES6 to ES5 for formal release like in npm? Thanks.

**Comment by shershen08** [comment]
Thank you for the detailed answer @pingshunhuangalex 

First - if as just a hot fix you try to replace

**Comment by pingshunhuangalex** [comment]
Hi @shershen08 
I just tried downloading your demo repo, `npm i` and `npm run build`. It spit out the same error as I expected. I think Vue-cli got everything we need in this case. It's UglifyJS that's causing the problem.

Do you mind I used your demo repo as a minimal setup for issue testing. I'll reference this issue to it.

Meanwhile, I think a good approach would be using babel to compile your entire script (which is just one file) down to ES5, so users won't be affected. Let me know if you have any better ideas. Thanks.

**Comment by shershen08** [comment]
I've created a branch, check this one - https://github.com/shershen08/vue-masonry/tree/compile-to-es5

**Comment by pingshunhuangalex** [comment]
Thanks @shershen08
By any chance you can put it in npm too?

**Comment by shershen08** [comment]
I will merge and publish to NPM today.

**Comment by pingshunhuangalex** [comment]
Hi @shershen08 

Just in case you missed the answer in the original thread, I copied and pasted it below. Since it's in beta, it requires some setup to get UglifyJS to minify ES6.

Personally, I would suggest you stick with ES5 for update release (you can still write in ES6 and compile), at least until they come out of beta so vue-cli actually include the setup for this feature or just include the instructions below in your documentation. Thanks.

```
The repo provided is using an old version of uglifyjs-webpack-plugin that uses uglify-js which is ES5 only:

https://github.com/shershen08/vue-masonry-plugin-demo/blob/34b213bb6b17130ddc0abde68cdb18294bc281af/package.json#L42

uglifyjs-webpack-plugin@1.0.0-beta.2 uses the ES6+ capable uglify-es module.

The repo's webpack@2.6.1 prod config is also pointing an ES5 only uglify-js webpack uglify plugin:

https://github.com/shershen08/vue-masonry-plugin-demo/blob/34b213bb6b17130ddc0abde68cdb18294bc281af/build/webpack.prod.conf.js#L32

See: https://stackoverflow.com/a/45088328
```

**Comment by shershen08** [comment]
updated it just now - https://www.npmjs.com/package/vue-masonry
**v 0.10.7**

**Comment by pingshunhuangalex** [comment]
Hi @shershen08 

I just tried 0.10.7, it still throws me the same error. I went into the compressed file in the dist, and I still see arrow functions...

**Comment by shershen08** [comment]
hmmm, gimme a sec

**Comment by shershen08** [comment]
Fixed this, https://www.npmjs.com/package/vue-masonry
@pingshunhuangalex could you check the **0.10.8** now?

**Comment by pingshunhuangalex** [comment]
Hi @shershen08 

0.10.8 does stop throwing out the bundling error, but the package is still broken. Check the errors shown up in the console. If I revert back to 0.10.6, everything works fine, so it's unlikely issues caused on my side. Thanks.
![image](https://user-images.githubusercontent.com/17170199/29196373-2febc4e6-7e77-11e7-9430-3b3a4f85d996.png)

**Comment by pingshunhuangalex** [comment]
Hi @shershen08 
I'm just gonna to do it in a very sloppy way by pasting the code below instead of forking and submit a PR.
Here is the compiled code for `masonry-plugin` file. Just starts with the latest working version `0.10.6`, and replace `masonry-plugin` with code below. It's all working on my side. Thanks.

```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.VueMasonryPlugin = undefined;

var _keys = require('babel-runtime/core-js/object/keys');

var _keys2 = _interopRequireDefault(_keys);

var _vue = require('vue');

var _vue2 = _interopRequireDefault(_vue);

var _masonryLayout = require('masonry-layout');

var _masonryLayout2 = _interopRequireDefault(_masonryLayout);

var _imagesloaded = require('imagesloaded');

var _imagesloaded2 = _interopRequireDefault(_imagesloaded);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var attributesMap = {
  'column-width': 'columnWidth',
  'transition-duration': 'transitionDuration',
  'item-selector': 'itemSelector',
  'origin-left': 'originLeft',
  'origin-top': 'originTop',
  'fit-width': 'fitWidth',
  'stamp': 'stamp',
  'gutter': 'gutter'
};
var EVENT_ADD = 'vuemasonry.itemAdded';
var EVENT_REMOVE = 'vuemasonry.itemRemoved';
var EVENT_IMAGE_LOADED = 'vuemasonry.imageLoaded';

var stringToBool = function stringToBool(val) {
  return (val + '').toLowerCase() === 'true';
};

var collectOptions = function collectOptions(attrs) {
  var res = {};
  var attributesArray = Array.prototype.slice.call(attrs);
  attributesArray.forEach(function (attr) {
    if ((0, _keys2.default)(attributesMap).indexOf(attr.name) > -1) {
      res[attributesMap[attr.name]] = attr.name.indexOf('origin') > -1 ? stringToBool(attr.value) : attr.value;
    }
  });
  return res;
};

var Events = new _vue2.default({});

var VueMasonryPlugin = exports.VueMasonryPlugin = function VueMasonryPlugin() {};

VueMasonryPlugin.install = function (Vue, options) {

  Vue.redrawVueMasonry = function () {
    Events.$emit(EVENT_ADD);
  };

  Vue.directive('masonry', {
    props: ['transitionDuration', ' itemSelector'],

    inserted: function inserted(el, nodeObj) {
      if (!_masonryLayout2.default) {
        throw new Error('Masonry plugin is not defined. Please check it\'s connected and parsed correctly.');
      }
      var masonry = new _masonryLayout2.default(el, collectOptions(el.attributes));
      var masonryDraw = function masonryDraw() {
        masonry.reloadItems();
        masonry.layout();
      };
      Vue.nextTick(function () {
        masonryDraw();
      });

      Events.$on(EVENT_ADD, function (eventData) {
        masonryDraw();
      });
      Events.$on(EVENT_REMOVE, function (eventData) {
        masonryDraw();
      });
      Events.$on(EVENT_IMAGE_LOADED, function (eventData) {
        masonryDraw();
      });
    }
  });

  Vue.directive('masonryTile', {

    inserted: function inserted(el) {
      Events.$emit(EVENT_ADD, {
        'element': el
      });

      new _imagesloaded2.default(el, function () {
        Events.$emit(EVENT_IMAGE_LOADED, {
          'element': el
        });
      });
    },
    beforeDestroy: function beforeDestroy(el) {
      Events.$emit(EVENT_REMOVE, {
        'element': el
      });
    }
  });
};
```

**Comment by shershen08** [comment]
@pingshunhuangalex thanks for your input. I'll make sure that code w/o error lands in fix version asap.

**Comment by pingshunhuangalex** [comment]
Hi @shershen08 
I know you are probably busy, but just checking if there is any update on this.

I didn't change any of your code above. All I do is compile the 0.10.6 to ES5. Thanks.

**Comment by shershen08** [comment]
@pingshunhuangalex sorry for not providing a reaction last days. I am struggling to create a build that will satisfy all the current and probable users:
There's no problem - I can built my ES6 code with webpack + es2015 preset and have a ES5 code like you posted earlier (https://github.com/shershen08/vue-masonry/issues/26#issuecomment-321959964).

**Comment by pingshunhuangalex** [comment]
So is it up? I know 0.10.8 already has the compiled ES5 code, but the error in the console indicates there may be some path issue for your new webpack settings.

If you can sort Webpack setting out, I'm fine with it. If it's gonna take some effort, replacing ES6 file in src with a compiled one using the same setup as 0.10.6 would be a nice shortcut.

I'll leave the decision to you. I'm loading a compiled version from static temporarily now, so take your time I guess...

**Comment by shershen08** [comment]
sorry, I'll write the details in some minutes, ok?

**Comment by pingshunhuangalex** [comment]
Yeah sure, all fine by me 👍

**Comment by shershen08** [comment]
@pingshunhuangalex  I've included your fix into the 0.10.10 version. I hope that solution helps the current users of the plugin. 
Also @andreliem @iamwill123 this is the update on the issue you've sumbitted #28

**Comment by impalervl** [comment]
Hi @shershen08 . I'm still having problems even with latest version(0.10.10) and it throws the following errors. I tried clearing cache and installing previous versions(0.10.5, 0.10.6 etc) which had no effect as well. It all seemed to work fine till the friday update. I'm using webpack v3.4.0, npm v3.10.10.
Do you have any ideas what could be wrong?
![_2017-08-16_15-21-59](https://user-images.githubusercontent.com/26309471/29362988-c45aee5e-8296-11e7-827d-f25e5f954252.png)

**Comment by pingshunhuangalex** [comment]
Hi @shershen08 
Just tested it out. All good.
You might want to change the documentation:
from
`import VueMasonryPlugin from 'vue-masonry';`
to
`import {VueMasonryPlugin} from 'vue-masonry';`

**Comment by shershen08** [comment]
@pingshunhuangalex you're totally right. Doing it now. 
Thanks again for your time helping out with this issue!
